import type { PortfolioConfig } from '../types/portfolio.ts'

const dummyCaseStudy = {
  overview: 'A production web product focused on clear workflows and a maintainable frontend system.',
  role: 'Frontend Developer',
  roleTags: ['UI systems', 'Product frontend'],
  problem: 'The existing interface could not scale with new operational requirements.',
  solution: 'A component-driven React application with typed APIs and a restrained visual system.',
  features: ['Reusable UI system', 'Responsive layouts', 'API-driven workflows'],
  technologies: ['React', 'TypeScript', 'Tailwind CSS'],
  decisions: [
    {
      challenge: 'Complexity leaked into every screen',
      decision: 'Shared primitives over one-off screens',
      outcome: 'Faster, calmer product surfaces',
    },
  ],
  screenshots: [] as string[],
  metrics: [
    { label: 'Focus', value: 'Product UI' },
    { label: 'Stack', value: 'React + TS' },
  ],
  pullQuote: 'Systems outlast individual pages.',
  results: ['Shipped a maintainable production interface'],
  learned: ['Systems outlast individual pages'],
}

export const friendTwoConfig: PortfolioConfig = {
  personal: {
    name: 'Marcus Chen',
    firstName: 'Marcus',
    lastName: 'Chen',
    initials: 'MC',
    jobTitle: 'Product Frontend Developer',
    tagline: 'Product Frontend Developer for billing-aware SaaS.',
    profileImage: '',
    resumeUrl: '',
    email: '',
    phone: '',
    location: 'Singapore',
    availability: 'Available for select projects',
    yearsOfExperience: '4+',
    projectCount: '10+',
  },
  seo: {
    siteUrl: 'https://example.com',
    title: 'Marcus Chen | Product Frontend Developer',
    description:
      'Product Frontend Developer specializing in React, TypeScript, Stripe-backed SaaS, and high-craft marketing-to-app experiences.',
    ogImage: '/og-image.png',
    keywords: ['React', 'TypeScript', 'Stripe', 'SaaS'],
  },
  hero: {
    availabilityBadge: 'Available for select projects',
    greeting: "Hi, I'm",
    description:
      'I build the product surfaces between marketing and billing — onboarding, dashboards, and payment flows that stay trustworthy under pressure.',
    primaryCta: { label: 'View My Work', href: '#projects' },
    secondaryCta: { label: 'Download Resume', href: '' },
    focusLine: 'Building product interfaces end to end',
  },
  about: {
    sectionNumber: '01',
    heading: 'Product UI that earns trust',
    description:
      'I focus on frontend systems where payments, permissions, and product analytics have to feel inevitable rather than bolted on.',
    image: '',
    valueCards: [
      { title: 'Trust', description: 'Billing and account states explained in plain language.' },
      { title: 'Pace', description: 'Interfaces that stay fast as product surface area grows.' },
      { title: 'Taste', description: 'A distinctive look without sacrificing usability.' },
      { title: 'Ownership', description: 'End-to-end delivery from prototype to production.' },
    ],
  },
  nav: [
    { label: 'Home', href: '/#home', sectionId: 'home' },
    { label: 'About', href: '/#about', sectionId: 'about' },
    { label: 'Projects', href: '/#projects', sectionId: 'projects' },
    { label: 'Experience', href: '/#experience', sectionId: 'experience' },
    { label: 'Skills', href: '/#skills', sectionId: 'skills' },
    { label: 'Contact', href: '/#contact', sectionId: 'contact' },
  ],
  stats: [
    { value: '4+', label: 'Years Experience' },
    { value: '10+', label: 'Production Projects' },
    { value: 'Stripe', label: 'Payment UX' },
  ],
  projectFilters: ['All', 'SaaS', 'Frontend', 'Full Stack'],
  projects: [
    {
      slug: 'emberpay',
      title: 'EmberPay',
      category: 'Billing Console',
      filters: ['SaaS', 'Full Stack'],
      shortDescription: 'A billing console for plans, invoices, and failed-payment recovery.',
      stack: ['React', 'TypeScript', 'Stripe'],
      image: '',
      liveUrl: '',
      githubUrl: '',
      featured: true,
      seoTitle: 'EmberPay | Marcus Chen',
      seoDescription: 'Billing console case study by Marcus Chen.',
      caseStudy: dummyCaseStudy,
    },
    {
      slug: 'harbor',
      title: 'Harbor',
      category: 'Customer Portal',
      filters: ['Frontend', 'SaaS'],
      shortDescription: 'A customer portal for usage, invoices, and self-serve plan changes.',
      stack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
      image: '',
      liveUrl: '',
      githubUrl: '',
      featured: false,
      seoTitle: 'Harbor | Marcus Chen',
      seoDescription: 'Customer portal case study by Marcus Chen.',
      caseStudy: dummyCaseStudy,
    },
  ],
  skills: [
    { id: 'frontend', label: 'Frontend', items: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'] },
    { id: 'integrations', label: 'Integrations', items: ['Stripe', 'REST APIs'] },
  ],
  competencies: ['Payment UX', 'SaaS Dashboards', 'Frontend Architecture', 'Responsive UI'],
  experience: [
    {
      company: 'Example Payments',
      role: 'Product Frontend Developer',
      period: '2022 – Present',
      location: 'Singapore',
      highlights: ['Owned billing and customer-portal interfaces for a SaaS platform.'],
    },
  ],
  education: [
    { degree: 'B.Sc. Computing', school: 'Example University', period: '2016 – 2020', detail: '' },
  ],
  socialLinks: [
    { id: 'github', label: 'GitHub', href: '' },
    { id: 'linkedin', label: 'LinkedIn', href: '' },
  ],
  contact: {
    heading: "Let's talk product",
    description: 'Available for teams shipping billing-aware SaaS.',
    form: {
      nameLabel: 'Name',
      emailLabel: 'Email',
      messageLabel: 'Message',
      submitLabel: 'Send Message',
      successMessage: 'Thanks — I will reply soon.',
      errorMessage: 'Unable to send right now. Please try again.',
      missingKeyMessage: 'The contact form is not connected yet.',
      subject: 'Portfolio contact from Marcus Chen',
    },
  },
  footer: { copyright: 'Marcus Chen', builtWith: 'Built with React + TypeScript' },
  theme: {
    mode: 'dark',
    primary: '#C97B5A',
    secondary: '#D4B8A0',
    background: '#14100E',
    surface: '#1C1714',
    surfaceSecondary: '#261E19',
    textPrimary: '#F6F0EA',
    textSecondary: '#B0A297',
    border: 'rgba(246,240,234,0.10)',
    success: '#8FAF6B',
  },
  cta: {
    letsTalk: "Let's Talk",
    viewWork: 'View My Work',
    openResume: 'Open Resume',
    downloadResume: 'Download Resume',
    viewCaseStudy: 'View case study',
    liveSite: 'Live website',
    sourceCode: 'GitHub',
  },
}
